#pragma once

#ifndef _LEXER_HPP_
#define _LEXER_HPP_

#include <string_view>
#include <vector>
#include <string>
#include <utility>
#include <stdexcept>
#include <array>

class Token {
 public:
  enum class Type {
    Identifier,
    Keyword,
    CharLiteral,
    StringLiteral,
    IntegerLiteral,
    Punctuation,
    Whitespace,
    Comment,
  };
  constexpr static std::array<Type, 8> types = {
    Type::Identifier, Type::Keyword, Type::CharLiteral, Type::StringLiteral,
    Type::IntegerLiteral, Type::Punctuation, Type::Whitespace, Type::Comment
  };
  Token();
  Token(Type t);
  Token(Type t, const std::string &v);
  void read_from(const std::string_view &);
  bool match(const Token&) const;

  Type type;
  std::string value;
};

/* generated by copilot */
class LexerError : public std::runtime_error {
 public:
  explicit LexerError(const std::string &message) : std::runtime_error(message) {}
};

std::pair<char, int> read_characters(const std::string_view &);
std::vector<Token> lex(const std::string_view &);

#endif