#pragma once

#ifndef _PARSE_RULES_HPP_
#define _PARSE_RULES_HPP_

enum class Nonterminal {
  ITEMS, 
  ITEM, 
  FUNCTION, 
    OPTIONAL_CONST, 
    FUNCTION_PARAMETERS,
    SELF_PARAM, 
    SHORTHAND_SELF,
    TYPED_SELF,
    FUNCTION_PARAM,
    FUNCTION_RETURN_TYPE,
      OPTIONAL_FUNCTION_PARAMETERS, 
      OPTIONAL_COMMA,
      COMMA_FUNCTION_PARAMS,
      OPTIONAL_FUNCTION_RETURN_TYPE,
      BLOCK_EXPRESSION_OR_SEMICOLON,
  STRUCT,
    STRUCT_FIELDS,
    STRUCT_FIELD,
      COMMA_STRUCT_FIELDS,
};

#endif