#pragma once

#ifndef _PARSE_RULES_HPP_
#define _PARSE_RULES_HPP_

enum class Nonterminal {
  ITEMS, 
  ITEM, 
  FUNCTION, 
    OPTIONAL_CONST, 
    FUNCTION_PARAMETERS,
    SELF_PARAM, 
    SHORTHAND_SELF,
    TYPED_SELF,
    FUNCTION_PARAM,
    FUNCTION_RETURN_TYPE,
      OPTIONAL_FUNCTION_PARAMETERS, 
      OPTIONAL_COMMA,
      COMMA_FUNCTION_PARAMS,
      OPTIONAL_FUNCTION_RETURN_TYPE,
      BLOCK_EXPRESSION_OR_SEMICOLON,
  STRUCT,
    STRUCT_FIELDS,
    STRUCT_FIELD,
      OPTIONAL_STRUCT_FIELDS,
      COMMA_STRUCT_FIELDS,
  ENUMERATION,
    ENUM_VARIANTS,
    ENUM_VARIANT,
      OPTIONAL_ENUM_VARIANTS,
      COMMA_ENUM_VARIANTS,
  CONSTANT_ITEM,
  TRAIT,
  IMPLEMENTATION,
    INHERENT_IMPL,
    TRAIT_IMPL,
  STATEMENT,
    LET_STATEMENT,
    EXPRESSION_STATEMENT,
};

#endif