#include "parse_rules.hpp"
#include "lexer.hpp"
#include <vector>
#include <array>
#include <variant>

// generated by copilot
// left-recursive grammar is preferred
// epsilon production is allowed
// the first rule is the start symbol
// rules are tried in order, the first matching rule is used
const std::array<std::vector<std::vector<std::variant<Token, Nonterminal>>>, 1> parse_rules = {
  // ITEMS -> ITEMS ITEM | epsilon
  {
    { Nonterminal::ITEMS, Nonterminal::ITEM },
    { }
  },
  // ITEM -> FUNCTION | STRUCT | ENUMERATION | CONSTANT_ITEM | TRAIT | IMPLEMENTATION
  {
    { Nonterminal::FUNCTION },
    { Nonterminal::STRUCT },
    { Nonterminal::ENUMERATION },
    { Nonterminal::CONSTANT_ITEM },
    { Nonterminal::TRAIT },
    { Nonterminal::IMPLEMENTATION },
  },
  // FUNCTION -> OPTIONAL_CONST "fn" Identifier "(" ")" "{" ITEMS "}"
  {
    { Nonterminal::OPTIONAL_CONST, Token(Token::Type::Keyword, "fn"), Token(Token::Type::Identifier), Token(Token::Type::Punctuation), Token(Token::Type::Punctuation), Token(Token::Type::Punctuation), Nonterminal::ITEMS, Token(Token::Type::Punctuation) }
  },
};